### ISSUE TITLE
june 16th meetup

### ISSUE THREAD

**Issue by aaronj1335** [austinjavascript/austinjavascript.github.io#14]
- [x] sponsor (have a verbal commitment)
- [x] speaker (have a speaker)
- [ ] blog post (#16)
- [x] space

**Comment by aaronj1335** [comment]
@AndyCouch is frog up for hosting austinjs on june 16th?

**Comment by AndyCouch** [comment]
@aaronj1335 Sure thing!

**Comment by aaronj1335** [comment]
thnx man!

**Comment by aaronj1335** [comment]
@getify do you have an abstract & bio you'd like me to include in the post?

**Comment by aaronj1335** [comment]
oh hey i guess i could just use [the nomadjs one](https://nomadjavascript.com/june-2015/) if that works.

**Comment by getify** [comment]
Yeah, that's exactly what I'd just copy-paste for you. ;-)

**Comment by aaronj1335** [comment]
:+1:

**Comment by AndyCouch** [comment]
Just a heads up...  I was supposed to travel for work this week and then it was tentatively pushed to next week. We're still not sure if it'll be next week or the week after. I've tried to find someone else at frog that could fill in for me in case I'm not here, but no one is available. So right now it's a 50/50 chance that we may not be able to have the meeting at frog next week, but I should know for sure by tomorrow or this weekend at the latest. I know that's not ideal, but I just wanted give you a heads up instead of springing it on you on Monday. I'll let you know as soon as I know for sure.

**Comment by aaronj1335** [comment]
Hey that's cool, just let us know ASAP so we can find a new spot if needed!

**Comment by getify** [comment]
So I take it we are confirmed for Frog?

**Comment by aaronj1335** [comment]
yep!

**Comment by aaronj1335** [comment]
will you have special av arrangements or anything? if so we'll need you and @AndyCouch to link up on that.

**Comment by AndyCouch** [comment]
Yeah!  Unless I get word this afternoon that I need to hop on a plane tomorrow morning, which is highly unlikely.

**Comment by getify** [comment]
I will just need to be able to connect to gotomeeting (that's how the video is broadcast to the nomadjs audience). If it's at all possible to be on wired internet, that'd be great. Otherwise, just need to verify that the guest network won't block a gotomeeting connection.

**Comment by AndyCouch** [comment]
We can't provide a wired connection (ports don't physically exist in the public space), but I'm fairly certainly we don't have any blocks on the public network. I'll double check to be sure.

**Comment by getify** [comment]
OK, maybe we can just ask attendees to reduce/limit their wifi usage while I'm broadcasting. :)

**Comment by aaronj1335** [comment]
mos def

**Comment by AndyCouch** [comment]
Just confirmed that there are no traffic restrictions out to the Internet from our guest network, so we should be good.

**Comment by getify** [comment]
<3
